function translateTextToNumbers(inputText) {
    const translationKey = {
        ' ' : '00, ',
        '.' : '42, ',
        ',' : '05, ',
        '<' : '50, ',
        '>' : '39, ',
        '/' : '27, ',
        '?' : '15, ',
        ';' : '18, ',
        ':' : '29, ',
        "'" : '47, ',
        '"' : '64, ',
        '|' : '61, ',
        '[' : '01, ',
        ']' : '06, ',
        '{' : '33, ',
        '}' : '21, ',
        '=' : '46, ',
        '+' : '03, ',
        '-' : '57, ',
        '_' : '20, ',
        '(' : '28, ',
        ')' : '59, ',
        '*' : '65, ',
        '&' : '60, ',
        '^' : '07, ',
        '%' : '17, ',
        '$' : '52, ',
        '#' : '37, ',
        '@' : '35, ',
        '!' : '10, ',
        '`' : '14, ',
        '~' : '54, ',
        '1' : '09, ',
        '2' : '31, ',
        '3' : '55, ',
        '4' : '45, ',
        '5' : '36, ',
        '6' : '66, ',
        '7' : '26, ',
        '8' : '51, ',
        '9' : '11, ',
        '0' : '56, ',
        'A' : '43, ',
        'B' : '34, ',
        'C' : '30, ',
        'D' : '63, ',
        'E' : '16, ',
        'F' : '19, ',
        'G' : '24, ',
        'H' : '44, ',
        'I' : '08, ',
        'J' : '32, ',
        'K' : '58, ',
        'L' : '49, ',
        'M' : '23, ',
        'N' : '41, ',
        'O' : '53, ',
        'P' : '02, ',
        'Q' : '25, ',
        'R' : '67, ',
        'S' : '38, ',
        'T' : '22, ',
        'U' : '48, ',
        'V' : '12, ',
        'W' : '04, ',
        'X' : '62, ',
        'Y' : '40, ',
        'Z' : '13, ',
        'a' : '38, ',
        'b' : '84, ',
        'c' : '16, ',
        'd' : '90, ',
        'e' : '87, ',
        'f' : '82, ',
        'g' : '79, ',
        'h' : '83, ',
        'i' : '88, ',
        'j' : '80, ',
        'k' : '89, ',
        'l' : '04, ',
        'm' : '44, ',
        'n' : '85, ',
        'o' : '99, ',
        'p' : '78, ',
        'q' : '91, ',
        'r' : '25, ',
        's' : '95, ',
        't' : '40, ',
        'u' : '32, ',
        'v' : '98, ',
        'w' : '68, ',
        'x' : '86, ',
        'y' : '81, ',
        'z' : '12, ',
    };

    let translatedText = '';

    for (let i = 0; i < inputText.length; i++) {
        const char = inputText.charAt(i);
        translatedText += translationKey[char] || char;
    }

    return translatedText;
}

function translateNumbersToText(inputNumbers) {
    const reverseTranslationKey = {
        '00,': ' ',
        '42,': '.',
        '05,': ',',
        '50,': '<',
        '39,': '>',
        '27,': '/',
        '15,': '?',
        '18,': ';',
        '29,': ':',
        '47,': "'",
        '64,': '"',
        '61,': '|',
        '01,': '[',
        '06,': ']',
        '33,': '{',
        '21,': '}',
        '46,': '=',
        '03,': '+',
        '57,': '-',
        '20,': '_',
        '28,': '(',
        '59,': ')',
        '65,': '*',
        '60,': '&',
        '07,': '^',
        '17,': '%',
        '52,': '$',
        '37,': '#',
        '35,': '@',
        '10,': '!',
        '14,': '`',
        '54,': '~',
        '09,': '1',
        '31,': '2',
        '55,': '3',
        '45,': '4',
        '36,': '5',
        '66,': '6',
        '26,': '7',
        '51,': '8',
        '11,': '9',
        '56,': '0',
        '43,': 'A',
        '34,': 'B',
        '30,': 'C',
        '63,': 'D',
        '16,': 'E',
        '19,': 'F',
        '24,': 'G',
        '44,': 'H',
        '08,': 'I',
        '32,': 'J',
        '58,': 'K',
        '49,': 'L',
        '23,': 'M',
        '41,': 'N',
        '53,': 'O',
        '02,': 'P',
        '25,': 'Q',
        '67,': 'R',
        '38,': 'S',
        '22,': 'T',
        '48,': 'U',
        '12,': 'V',
        '04,': 'W',
        '62,': 'X',
        '40,': 'Y',
        '13,': 'Z',
        '38,': 'a',
        '84,': 'b',
        '16,': 'c',
        '90,': 'd',
        '87,': 'e',
        '82,': 'f',
        '79,': 'g',
        '83,': 'h',
        '88,': 'i',
        '80,': 'j',
        '89,': 'k',
        '04,': 'l',
        '44,': 'm',
        '85,': 'n',
        '99,': 'o',
        '78,': 'p',
        '91,': 'q',
        '25,': 'r',
        '95,': 's',
        '40,': 't',
        '32,': 'u',
        '98,': 'v',
        '68,': 'w',
        '86,': 'x',
        '81,': 'y',
        '12,': 'z'
    };

    const translatedNumbers = inputNumbers.split(', ').map(number => reverseTranslationKey[number] || number);
    const translatedText = translatedNumbers.join('');
    return translatedText;
}

document.getElementById('input-text').addEventListener('input', function() {
    const inputText = this.value;
    const translatedText = translateTextToNumbers(inputText);
    document.getElementById('output-text').value = translatedText;
});

document.getElementById('input-number').addEventListener('input', function() {
    const inputNumbers = this.value;
    const translatedText = translateNumbersToText(inputNumbers);
    document.getElementById('output-number').value = translatedText;
});
